services:
  openwebrx:
    image: jketterl/openwebrx-hackrf:latest
    privileged: true
    restart: unless-stopped
    network_mode: host
    devices:
      - /dev/bus/usb:/dev/bus/usb
    volumes:
      - ./openwebrx_data:/var/lib/openwebrx

  hackrf-sweep:
    build:
      context: ./hackrf-sweep
      dockerfile: Dockerfile
    container_name: hackrf-sweep
    restart: unless-stopped
    command: >
      bash -lc "mkdir -p /var/log/hackrf &&
                exec hackrf_sweep -f 1:6000 -w 10000000
                -r /var/log/hackrf/hackrf_sweep.csv"
    volumes:
      - ./sweep_logs:/var/log/hackrf
    devices:
      - /dev/bus/usb:/dev/bus/usb
