services:
  openwebrx:
    image: slechev/openwebrxplus:latest
    container_name: openwebrx
    devices:
      - /dev/bus/usb:/dev/bus/usb
    environment:
      OPENWEBRX_ADMIN_USER: admin
      OPENWEBRX_ADMIN_PASSWORD: STRONG_PASSWORD
    volumes:
      - ./openwebrx_data:/var/lib/openwebrx
    restart: unless-stopped
    profiles: ["ui"]
    # removed depends_on to avoid starting sweep with UI

  hackrf-sweep:
    image: debian:stable-slim
    profiles: ["sweep"]
    privileged: true
    network_mode: host
    restart: unless-stopped
    devices:
      - /dev/bus/usb:/dev/bus/usb
    volumes:
      - /mnt/iqdata:/mnt/iqdata
    command: >
      bash -lc "
        set -euo pipefail;
        apt-get update -qq &&
        apt-get install -y --no-install-recommends hackrf coreutils gawk &&
        mkdir -p /mnt/iqdata/sweeps;
        while true; do
          ts=$$(date -u +%Y%m%dT%H%M%SZ);
          raw=/mnt/iqdata/sweeps/sweep_$${ts}.csv;
          lite=/mnt/iqdata/sweeps/sweep_$${ts}_lite.csv;
          echo '>> sweep' $$ts;
          timeout 60 hackrf_sweep -f 1:6000 -w 100000 -a 1 -l 32 -g 24 -r $$raw || true;
          awk -F', *' '{
            low=$$3+0; high=$$4+0; bw=$$5+0;
            max=-1e9; idx=-1; sum=0; cnt=0;
            for(i=7;i<=NF;i++){v=$$i+0; sum+=v; cnt++; if(v>max){max=v; idx=i-7}}
            if(cnt>0){
              peak_hz=low + (idx+0.5)*bw; mean=sum/cnt;
              printf \"%sT%sZ,%.0f,%.0f,%.2f,%d,%.0f,%.2f,%.2f\\n\", $$1, $$2, low, high, bw, cnt, peak_hz, max, mean;
            }
          }' $$raw > $$lite;
          # keep last 14 days (~20160 minutes)
          ls -1tr /mnt/iqdata/sweeps/sweep_*.csv | head -n -20160 | xargs -r rm -f;
          ls -1tr /mnt/iqdata/sweeps/sweep_*_lite.csv | head -n -20160 | xargs -r rm -f;
        done"

  hackrf-watch:
    image: debian:stable-slim
    container_name: hackrf-watch
    devices:
      - /dev/bus/usb:/dev/bus/usb
    volumes:
      - /mnt/iqdata:/data
    command: >
      bash -lc "
        set -euo pipefail;
        apt-get update -qq &&
        apt-get install -y --no-install-recommends hackrf coreutils;
        rate=8000000;
        while true; do
          ts=$$(date -u +%Y%m%dT%H%M%SZ);
          base=1600;  # MHz
          while [ $$base -lt 1700 ]; do
            next=$$((base+20));
            out=/data/watch_$${ts}_$${base}-$${next}.iq;
            echo Recording $$out;
            center=$$(( (base+10)*1000000 ));
            hackrf_transfer -r - -f $$center -s $$rate -a 1 -l 32 -g 24 -b 10000000 \
              -n $$((rate*2*60)) > $$out;
            base=$$next;
          done
          find /data -type f -name 'watch_*.iq' -printf '%T+ %p\n' \
            | sort | head -n -20160 | cut -d' ' -f2- | xargs -r rm -f;
        done
      "
    restart: unless-stopped
    profiles: ["watch"]

  nginx:
    image: nginx:alpine
    ports:
      - "443:443"
    volumes:
      - ./certs:/etc/nginx/certs:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - openwebrx
    restart: unless-stopped
    profiles: ["ui"]
