services:
  openwebrx:
    image: slechev/openwebrxplus:latest
    container_name: openwebrx
    devices:
      - /dev/bus/usb:/dev/bus/usb
    # ports:                      # optional: disable if only using https via nginx
    #   - "8073:8073"
    environment:
      OPENWEBRX_ADMIN_USER: admin
      OPENWEBRX_ADMIN_PASSWORD: STRONG_PASSWORD
    volumes:
      - ./openwebrx_data:/var/lib/openwebrx
    restart: unless-stopped

  # optional; DO NOT run at the same time as OpenWebRX
  hackrf-sweep:
    image: debian:stable-slim
    profiles: ["sweep"]
    privileged: true
    network_mode: host
    restart: unless-stopped
    devices:
      - /dev/bus/usb:/dev/bus/usb
    volumes:
      - ./sweep_logs:/var/log/hackrf
    command: >
      bash -lc "apt-get update &&
                apt-get install -y --no-install-recommends hackrf &&
                mkdir -p /var/log/hackrf &&
                exec hackrf_sweep -f 1:6000 -w 10000000 -r /var/log/hackrf/hackrf_sweep.csv"

  nginx:
    image: nginx:alpine
    ports:
      - "443:443"
      # (optional) redirect 80->443:
      # - "80:80"
    volumes:
      - ./certs:/etc/nginx/certs:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - openwebrx
    restart: unless-stopped
